### ISSUE TITLE
Where is trace repo

### ISSUE THREAD

**Issue by LilyaBu** [zyedidia/perforator#1]
hello, @zyedidia . I would like to try perforator tool.  go get depends on utrace repo, but seems utrace absent. Is this a necessary dependency or is there an alternative?

**Comment by zyedidia** [comment]
Thank you for telling me about the issue. The utrace package is provided in the `pkg` directory but was imported incorrectly (it assumed a non-go get installation). I have fixed it now -- let me know if you find another issue.
