### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AlexGustafsson** [zyedidia/perforator#3]
This is no issue per say, but I'd just like to sincerely thank you for providing this tool. As I'm sure you've experienced first hand, using `perf_event_open` and the related tooling can be a big hassle. I've spent countless hours implementing `perf_event_open` in C for micro-benchmarks and as many hours reading up on the `perf` tool. The custom code I wrote worked great, but it was cumbersome to manually instrument the source code. The `perf` tool is great - but it lacks one important factor; the ability to run `perf stat` for a specific function that may be somewhere along the lifecycle of the program. Sure, `perf record` provides similar functionality, but it is not necessarily easy to convert the measurements to actual values. Your tool solves all of this, and for that I'm truly grateful.

**Comment by AlexGustafsson** [comment]
Closing.

**Comment by zyedidia** [comment]
Thanks for the nice message! I'm glad the tool could be useful to you.
